package io.unlegit.utils.io;

import java.io.*;
import java.nio.file.Files;

/**
 * This class reads .nbs files, which are
 * generated by Minecraft Note Block Studio
 */
public class NbsReader
{
    public static NbsData read(File nbs)
    {
        int tempo = 0;
        
        try (DataInputStream stream = new DataInputStream(Files.newInputStream(nbs.toPath())))
        {
            stream.readShort();
            stream.readByte(); // Version
        }
        
        catch (IOException e) { e.printStackTrace(); }
        
        return new NbsData(tempo);
    }
    
    public static record NbsData(int tempo) {}
}
